# Generated by Django 5.1 on 2025-11-06 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tienda', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('ciudad', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=10)),
                ('telefono_tienda', models.CharField(blank=True, max_length=20)),
                ('fecha_apertura', models.DateField(blank=True, null=True)),
                ('es_drive_thru', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('puesto', models.CharField(max_length=50)),
                ('fecha_contratacion', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono_personal', models.CharField(blank=True, max_length=20)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajadores', to='app_InNOut.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('numero_orden', models.PositiveIntegerField()),
                ('total_pedido', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tipo_orden', models.CharField(help_text='Comer ahí o Para llevar', max_length=50)),
                ('nombre_cliente_temporal', models.CharField(blank=True, max_length=100)),
                ('pagado', models.BooleanField(default=False)),
                ('trabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='app_InNOut.trabajador')),
            ],
        ),
    ]
