# Generated by Django 5.2.8 on 2025-11-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_InNOut', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
