# Generated by Django 5.2.8 on 2025-11-18 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_InNOut', '0002_alter_trabajador_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('HAMBURGUESAS', 'Hamburguesas'), ('BEBIDAS', 'Bebidas'), ('PAPAS', 'Papas'), ('POSTRES', 'Postres'), ('COMBOS', 'Combos')], max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('disponible', models.BooleanField(default=True)),
                ('imagen', models.CharField(blank=True, help_text='URL de la imagen', max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.TextField()),
                ('tipo_proveedor', models.CharField(choices=[('ALIMENTOS', 'Alimentos'), ('BEBIDAS', 'Bebidas'), ('LIMPIEZA', 'Limpieza'), ('EQUIPOS', 'Equipos')], max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='es_drive_thru',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='fecha_apertura',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='telefono_tienda',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('unidad_medida', models.CharField(default='unidades', max_length=20)),
                ('stock_minimo', models.PositiveIntegerField(default=10)),
                ('ubicacion', models.CharField(default='Almacén principal', max_length=50)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('lote', models.CharField(blank=True, max_length=50)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='app_InNOut.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='app_InNOut.proveedor')),
            ],
        ),
    ]
