# Generated by Django 5.1 on 2025-11-20 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_InNOut', '0003_producto_proveedor_alter_sucursal_codigo_postal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='inventario',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='ubicacion',
            field=models.CharField(choices=[('Almacén principal', 'Almacén principal'), ('Almacén secundario', 'Almacén secundario')], default='Almacén principal', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='unidad_medida',
            field=models.CharField(choices=[('Unidad', 'Unidad'), ('kg', 'Kilogramos'), ('lt', 'Litros')], default='Unidad', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='nombre_cliente_temporal',
            field=models.CharField(blank=True, help_text='Usar si el cliente no está registrado', max_length=100),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo_orden',
            field=models.CharField(choices=[('Comer aqui', 'Comer aquí'), ('Para llevar', 'Para llevar')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total_pedido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='app_InNOut.cliente'),
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio al momento de la compra', max_digits=6)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app_InNOut.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_InNOut.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tarjeta', models.CharField(max_length=20, unique=True)),
                ('puntos_acumulados', models.PositiveIntegerField(default=0)),
                ('fecha_expiracion', models.DateField()),
                ('nivel', models.CharField(choices=[('Oro', 'Oro'), ('Platino', 'Platino')], default='Oro', max_length=20)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membresia', to='app_InNOut.cliente')),
            ],
        ),
    ]
